// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexerForm.flex

package backend.reglasGram;
import backend.objetos.*;
import java_cup.runtime.*;
import static backend.reglasGram.symForm.*;
import java.util.ArrayList;
import java.util.List;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexerForm implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\1\0\1\5\3\0\1\6\1\7\2\0"+
    "\1\10\1\5\1\11\1\12\12\13\1\14\6\0\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\2\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\26\1\42\2\26\1\43"+
    "\1\44\1\45\1\0\1\46\1\0\1\47\1\50\1\26"+
    "\1\51\1\26\1\52\1\26\1\53\1\54\2\26\1\55"+
    "\1\56\1\26\1\57\1\60\1\26\1\61\1\62\1\63"+
    "\1\64\5\26\1\65\1\66\1\67\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\1\1\4\1\10\14\4\1\11\1\12\2\4\1\13"+
    "\1\14\2\0\1\4\1\15\10\4\1\16\12\4\2\0"+
    "\2\4\1\0\21\4\1\17\21\4\1\20\6\4\1\21"+
    "\4\4\1\22\13\4\1\0\10\4\1\23\1\24\4\4"+
    "\1\25\21\4\1\26\6\4\1\27\1\30\13\4\1\31"+
    "\3\4\1\32\1\4\1\33\1\4\1\34\17\4\1\35"+
    "\5\4\1\36\1\37\3\4\1\40\1\4\1\41\3\4"+
    "\1\42\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\70\0\160\0\70\0\250\0\70\0\70"+
    "\0\70\0\340\0\u0118\0\70\0\u0150\0\u0188\0\u01c0\0\u01f8"+
    "\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u0310\0\u0348\0\u0380\0\u03b8"+
    "\0\70\0\70\0\u03f0\0\u0428\0\70\0\70\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658"+
    "\0\u0690\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818"+
    "\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8"+
    "\0\u0a10\0\340\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60"+
    "\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20"+
    "\0\u0d58\0\u0d90\0\u0dc8\0\u0118\0\u0e00\0\u0e38\0\u0e70\0\u0ea8"+
    "\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068"+
    "\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u0118\0\u11b8\0\u11f0"+
    "\0\u1228\0\u1260\0\u1298\0\u12d0\0\u0118\0\u1308\0\u1340\0\u1378"+
    "\0\u13b0\0\u0118\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500"+
    "\0\u1538\0\u1570\0\u15a8\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0"+
    "\0\u16f8\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u0118\0\u1848"+
    "\0\u1880\0\u18b8\0\u18f0\0\u1928\0\u0118\0\u1960\0\u1998\0\u19d0"+
    "\0\u1a08\0\u1a40\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58\0\u1b90"+
    "\0\u1bc8\0\u1c00\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0\0\u0118\0\u1d18"+
    "\0\u1d50\0\u1d88\0\u1dc0\0\u1df8\0\u1e30\0\u0118\0\u0118\0\u1e68"+
    "\0\u1ea0\0\u1ed8\0\u1f10\0\u1f48\0\u1f80\0\u1fb8\0\u1ff0\0\u2028"+
    "\0\u2060\0\u2098\0\u0118\0\u20d0\0\u2108\0\u2140\0\u0118\0\u2178"+
    "\0\u0118\0\u21b0\0\u0118\0\u21e8\0\u2220\0\u2258\0\u2290\0\u22c8"+
    "\0\u2300\0\u2338\0\u2370\0\u23a8\0\u23e0\0\u2418\0\u2450\0\u2488"+
    "\0\u24c0\0\u24f8\0\u0118\0\u2530\0\u2568\0\u25a0\0\u25d8\0\u2610"+
    "\0\u0118\0\u0118\0\u2648\0\u2680\0\u26b8\0\u0118\0\u26f0\0\u0118"+
    "\0\u2728\0\u2760\0\u2798\0\u0118\0\u0118";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\6\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\16\1\23\3\16\1\24\1\25\2\16"+
    "\1\26\1\16\1\27\1\30\2\16\1\31\1\12\1\32"+
    "\1\6\2\16\1\33\1\16\1\34\11\16\1\35\1\2"+
    "\1\36\72\0\1\3\72\0\1\6\3\0\1\6\1\0"+
    "\1\6\1\0\26\6\3\0\17\6\1\0\1\37\14\0"+
    "\1\40\1\0\26\40\4\0\16\40\4\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\26\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\42\12\13\1\43"+
    "\13\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\42"+
    "\26\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\42"+
    "\12\13\1\44\2\13\1\45\10\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\42\1\46\25\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\42\21\13\1\47\4\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\42\4\13"+
    "\1\50\3\13\1\51\4\13\1\52\10\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\42\3\13\1\53\10\13"+
    "\1\54\11\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\42\15\13\1\55\10\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\42\16\13\1\56\7\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\42\4\13\1\57\21\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\42\4\13"+
    "\1\60\3\13\1\61\15\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\42\20\13\1\62\1\63\4\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\42\26\13\1\0"+
    "\1\41\1\0\2\13\1\64\14\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\42"+
    "\26\13\1\0\1\41\1\0\15\13\1\65\1\13\1\0"+
    "\1\37\2\0\2\66\1\67\1\0\1\6\3\0\1\6"+
    "\1\0\1\70\1\0\26\70\3\0\1\6\16\70\4\0"+
    "\3\40\1\0\1\40\3\0\1\40\1\41\1\40\1\0"+
    "\26\40\1\0\1\41\1\0\17\40\16\0\1\71\1\0"+
    "\26\71\4\0\16\71\15\0\1\72\1\40\1\0\26\40"+
    "\1\0\1\72\2\0\16\40\4\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\10\13\1\73\15\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\1\74"+
    "\25\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\12\13\1\75\13\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\22\13\1\76\3\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\22\13\1\77\3\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\2\13\1\100"+
    "\23\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\12\13\1\101\13\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\20\13\1\102\5\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\26\13\1\0\1\41\1\0"+
    "\1\103\16\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\3\13\1\104\22\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\13\13"+
    "\1\105\12\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\2\13\1\106\23\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\6\13\1\107\10\13\1\110\6\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\13\13"+
    "\1\111\11\13\1\112\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\22\13\1\113\3\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\12\13\1\114\13\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\23\13\1\115"+
    "\2\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\116\1\41\1\13\1\0"+
    "\26\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\26\13\1\0\1\41\1\0\15\13\1\117\1\13\1\0"+
    "\1\37\6\0\1\6\3\0\1\6\1\0\1\70\1\0"+
    "\26\70\3\0\1\6\16\70\5\0\1\66\2\0\1\6"+
    "\3\0\1\6\1\0\1\70\1\0\26\70\3\0\1\6"+
    "\16\70\4\0\3\70\1\0\1\70\3\0\1\70\1\0"+
    "\1\70\1\0\26\70\3\0\17\70\1\0\1\37\2\0"+
    "\3\71\1\0\1\71\3\0\1\71\1\41\1\71\1\0"+
    "\26\71\1\0\1\41\1\0\17\71\4\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\14\13\1\120"+
    "\11\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\21\13\1\121\4\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\23\13\1\122\2\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\15\13\1\123\10\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\20\13\1\124"+
    "\5\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\7\13\1\125\16\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\1\126\25\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\13\13\1\127\12\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\5\13\1\130\20\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\10\13"+
    "\1\131\15\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\1\13\1\132\24\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\10\13\1\133\15\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\10\13\1\134\15\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\23\13"+
    "\1\135\2\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\1\136\25\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\22\13\1\137\3\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\23\13\1\140\2\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\1\141\25\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\26\13"+
    "\1\0\1\41\1\0\4\13\1\142\12\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\26\13\1\0\1\41\1\0\12\13\1\143\4\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\4\13\1\144\21\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\4\13\1\145\21\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\13\13"+
    "\1\146\12\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\21\13\1\147\4\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\23\13\1\150\2\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\1\151\25\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\21\13\1\152"+
    "\4\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\23\13\1\153\2\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\15\13\1\154\10\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\2\13\1\155\23\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\20\13\1\156"+
    "\5\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\15\13\1\157\10\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\21\13\1\160\4\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\4\13\1\161\21\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\15\13\1\162"+
    "\10\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\12\13\1\163\13\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\20\13\1\164\5\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\26\13\1\0\1\41\1\0"+
    "\11\13\1\165\5\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\166\26\13\1\0"+
    "\1\41\1\0\14\13\1\167\2\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\1\170\25\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\14\13\1\171\11\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\26\13\1\0\1\41\1\0\1\172"+
    "\16\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\2\13\1\173\23\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\26\13\1\0"+
    "\1\41\1\0\1\174\16\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\12\13"+
    "\1\175\13\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\20\13\1\176\5\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\4\13\1\177\21\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\4\13\1\200\21\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\14\13"+
    "\1\201\11\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\22\13\1\202\3\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\20\13\1\203\5\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\26\13\1\0\1\41"+
    "\1\0\1\204\16\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\15\13\1\205"+
    "\10\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\10\13\1\206\15\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\26\13\1\0\1\41\1\0\13\13\1\207"+
    "\3\13\1\0\1\37\13\0\1\42\56\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\166\26\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\2\13\1\210"+
    "\23\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\1\211\25\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\20\13\1\212\5\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\22\13\1\213\3\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\2\13\1\214\23\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\1\215"+
    "\25\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\13\13\1\216\12\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\26\13\1\0\1\41\1\0\1\217\16\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\4\13\1\220\21\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\20\13\1\221\5\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\10\13"+
    "\1\222\15\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\24\13\1\223\1\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\15\13\1\224\10\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\26\13\1\0\1\41"+
    "\1\0\10\13\1\225\6\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\10\13"+
    "\1\226\15\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\21\13\1\227\4\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\4\13\1\230\21\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\23\13\1\231\2\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\20\13"+
    "\1\232\5\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\20\13\1\233\5\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\23\13\1\234\2\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\2\13\1\235\23\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\21\13"+
    "\1\236\4\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\15\13\1\237\10\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\3\13\1\240\22\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\10\13\1\241\15\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\26\13"+
    "\1\0\1\41\1\0\1\242\16\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\26\13\1\0\1\41\1\0\16\13\1\243\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\15\13\1\244\10\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\2\13\1\245\23\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\20\13\1\246\5\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\4\13"+
    "\1\247\21\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\10\13\1\250\15\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\12\13\1\251\13\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\1\252\25\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\15\13\1\253"+
    "\10\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\21\13\1\254\4\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\2\13\1\255\23\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\26\13\1\0\1\41\1\0"+
    "\7\13\1\256\7\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\14\13\1\257"+
    "\11\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\15\13\1\260\10\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\1\261\25\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\1\262\25\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\15\13\1\263\10\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\1\264\25\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\13\13"+
    "\1\265\12\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\10\13\1\266\15\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\20\13\1\267\5\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\26\13\1\0\1\41"+
    "\1\0\1\13\1\270\15\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\16\13"+
    "\1\271\7\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\2\13\1\272\23\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\20\13\1\273\5\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\16\13\1\274\7\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\1\13"+
    "\1\275\24\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\4\13\1\276\21\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\26\13\1\0\1\41\1\0\13\13"+
    "\1\277\3\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\10\13\1\300\15\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\10\13"+
    "\1\301\15\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\10\13\1\302\15\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\15\13\1\303\10\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\12\13\1\304\13\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\1\305"+
    "\25\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\26\13\1\0\1\41\1\0\6\13\1\306\10\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\12\13\1\307\13\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\15\13\1\310\10\13\1\0"+
    "\1\41\1\0\17\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\15\13\1\311"+
    "\10\13\1\0\1\41\1\0\17\13\1\0\1\37\2\0"+
    "\3\13\1\0\1\13\3\0\1\13\1\41\1\13\1\0"+
    "\4\13\1\312\21\13\1\0\1\41\1\0\17\13\1\0"+
    "\1\37\2\0\3\13\1\0\1\13\3\0\1\13\1\41"+
    "\1\13\1\0\2\13\1\313\23\13\1\0\1\41\1\0"+
    "\17\13\1\0\1\37\2\0\3\13\1\0\1\13\3\0"+
    "\1\13\1\41\1\13\1\0\26\13\1\0\1\41\1\0"+
    "\11\13\1\314\5\13\1\0\1\37\2\0\3\13\1\0"+
    "\1\13\3\0\1\13\1\41\1\13\1\0\1\315\25\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\14\13"+
    "\1\316\11\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\10\13\1\317\15\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\26\13\1\0\1\41\1\0\14\13"+
    "\1\320\2\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\3\13\1\321\22\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\2\0\3\13"+
    "\1\0\1\13\3\0\1\13\1\41\1\13\1\0\15\13"+
    "\1\322\10\13\1\0\1\41\1\0\17\13\1\0\1\37"+
    "\2\0\3\13\1\0\1\13\3\0\1\13\1\41\1\13"+
    "\1\0\15\13\1\323\10\13\1\0\1\41\1\0\17\13"+
    "\1\0\1\37\2\0\3\13\1\0\1\13\3\0\1\13"+
    "\1\41\1\13\1\0\14\13\1\324\11\13\1\0\1\41"+
    "\1\0\17\13\1\0\1\37\2\0\3\13\1\0\1\13"+
    "\3\0\1\13\1\41\1\13\1\0\21\13\1\325\4\13"+
    "\1\0\1\41\1\0\17\13\1\0\1\37\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10192];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\3\11\2\1\1\11"+
    "\14\1\2\11\2\1\2\11\2\0\25\1\2\0\2\1"+
    "\1\0\73\1\1\0\137\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerForm(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return new java_cup.runtime.Symbol(symForm.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(ERROR,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 36: break;
          case 2:
            { /* ignorar */
            }
            // fall through
          case 37: break;
          case 3:
            { return new Symbol(COMILLA,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 38: break;
          case 4:
            { return new Symbol(STRING,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 39: break;
          case 5:
            { return new Symbol(PAI,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 40: break;
          case 6:
            { return new Symbol(PAD,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 41: break;
          case 7:
            { return new Symbol(COMA,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 42: break;
          case 8:
            { return new Symbol(DOS_PUNTOS,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 43: break;
          case 9:
            { return new Symbol(CORI,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 44: break;
          case 10:
            { return new Symbol(CORD,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 45: break;
          case 11:
            { return new Symbol(LLAI,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 46: break;
          case 12:
            { return new Symbol(LLAD,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1));
            }
            // fall through
          case 47: break;
          case 13:
            { 
            }
            // fall through
          case 48: break;
          case 14:
            { return new Symbol(ID_COMP,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 49: break;
          case 15:
            { return new Symbol(URL,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 50: break;
          case 16:
            { return new Symbol(TEMA,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 51: break;
          case 17:
            { return new Symbol(CLASE,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 52: break;
          case 18:
            { return new Symbol(FILAS,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 53: break;
          case 19:
            { return new Symbol(INDICE,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 54: break;
          case 20:
            { return new Symbol(NOMBRE,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 55: break;
          case 21:
            { return new Symbol(TITULO,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 56: break;
          case 22:
            { return new Symbol(COLUMNAS,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 57: break;
          case 23:
            { return new Symbol(OPCIONES,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 58: break;
          case 24:
            { return new Symbol(REGISTRO,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 59: break;
          case 25:
            { return new Symbol(REQUERIDO,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 60: break;
          case 26:
            { return new Symbol(ALINEACION,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 61: break;
          case 27:
            { return new Symbol(ESTRUCTURA,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 62: break;
          case 28:
            { return new Symbol(FORMULARIO,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 63: break;
          case 29:
            { return new Symbol(NOMBRE_CAMPO,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 64: break;
          case 30:
            { return new Symbol(ID_FORM,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 65: break;
          case 31:
            { return new Symbol(TEXTO_VISIBLE,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 66: break;
          case 32:
            { return new Symbol(FECHA_CREACION,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 67: break;
          case 33:
            { return new Symbol(DB_FORMULARIOS,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 68: break;
          case 34:
            { return new Symbol(USER_CREACION,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 69: break;
          case 35:
            { return new Symbol(DATOS_RECOPILADOS,yyline+1,yycolumn+1, new Token(yytext(),yyline+1,yycolumn+1 ));
            }
            // fall through
          case 70: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
