
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.reglasGram;

/** CUP generated class containing symbol constants. */
public class symForm {
  /* terminals */
  public static final int LLAD = 19;
  public static final int CORI = 7;
  public static final int FORMULARIO = 5;
  public static final int TEXTO_VISIBLE = 24;
  public static final int REQUERIDO = 26;
  public static final int FECHA_CREACION = 16;
  public static final int CORD = 8;
  public static final int ID_COMP = 20;
  public static final int DB_FORMULARIOS = 2;
  public static final int ERROR = 34;
  public static final int URL = 30;
  public static final int CLASE = 22;
  public static final int DOS_PUNTOS = 6;
  public static final int ID_FORM = 11;
  public static final int USER_CREACION = 15;
  public static final int FILAS = 28;
  public static final int STRING = 33;
  public static final int TEMA = 14;
  public static final int COMA = 9;
  public static final int ALINEACION = 25;
  public static final int NOMBRE = 13;
  public static final int EOF = 0;
  public static final int REGISTRO = 32;
  public static final int COMILLA = 10;
  public static final int DATOS_RECOPILADOS = 31;
  public static final int error = 1;
  public static final int INDICE = 23;
  public static final int PAI = 3;
  public static final int COLUMNAS = 29;
  public static final int LLAI = 18;
  public static final int PAD = 4;
  public static final int TITULO = 12;
  public static final int NOMBRE_CAMPO = 21;
  public static final int OPCIONES = 27;
  public static final int ESTRUCTURA = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DB_FORMULARIOS",
  "PAI",
  "PAD",
  "FORMULARIO",
  "DOS_PUNTOS",
  "CORI",
  "CORD",
  "COMA",
  "COMILLA",
  "ID_FORM",
  "TITULO",
  "NOMBRE",
  "TEMA",
  "USER_CREACION",
  "FECHA_CREACION",
  "ESTRUCTURA",
  "LLAI",
  "LLAD",
  "ID_COMP",
  "NOMBRE_CAMPO",
  "CLASE",
  "INDICE",
  "TEXTO_VISIBLE",
  "ALINEACION",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "URL",
  "DATOS_RECOPILADOS",
  "REGISTRO",
  "STRING",
  "ERROR"
  };
}

