
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.reglasGram;

/** CUP generated class containing symbol constants. */
public class symUser {
  /* terminals */
  public static final int COMA = 10;
  public static final int LLAD = 4;
  public static final int CORD = 9;
  public static final int USUARIO = 7;
  public static final int USER = 11;
  public static final int ERROR = 16;
  public static final int STRING = 15;
  public static final int FECHA_MODIFICACION = 14;
  public static final int EOF = 0;
  public static final int DB_USERS = 2;
  public static final int error = 1;
  public static final int PASS = 12;
  public static final int FECHA_CREACION = 13;
  public static final int DOS_PUNTOS = 5;
  public static final int LLAI = 3;
  public static final int CORI = 8;
  public static final int COMILLA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DB_USERS",
  "LLAI",
  "LLAD",
  "DOS_PUNTOS",
  "COMILLA",
  "USUARIO",
  "CORI",
  "CORD",
  "COMA",
  "USER",
  "PASS",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "STRING",
  "ERROR"
  };
}

