
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.reglasGram;

/** CUP generated class containing symbol constants. */
public class symIndigo {
  /* terminals */
  public static final int MAQ = 5;
  public static final int NUEVO_FORMULARIO = 15;
  public static final int FIN_SOLICITUD = 10;
  public static final int CONSULTA_N = 42;
  public static final int INI_SOLICITUDES = 4;
  public static final int FIN_SOLICITUDES = 6;
  public static final int DOS_PUNTOS = 8;
  public static final int MODIFICAR_USUARIO = 12;
  public static final int CONT_URL = 41;
  public static final int MENQ = 2;
  public static final int CREDENCIALES_USUARIO = 21;
  public static final int TITULO = 35;
  public static final int FORMULARIO = 36;
  public static final int LLAI = 27;
  public static final int CREAR_USUARIO = 11;
  public static final int ID = 32;
  public static final int CONT_CONSULTA = 43;
  public static final int LLAD = 28;
  public static final int CONT_OPCIONES = 39;
  public static final int EOF = 0;
  public static final int COMILLAS = 24;
  public static final int CONT_ID = 33;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int ELIMINAR_USUARIO = 13;
  public static final int URL = 40;
  public static final int ADMIRACION = 3;
  public static final int INI_SOLICITUD = 7;
  public static final int CONSULTAR_DATOS = 9;
  public static final int PARAMETROS_COMPONENTE = 23;
  public static final int MODIFICAR_COMPONENTE = 20;
  public static final int MODIFICAR_FORMULARIO = 17;
  public static final int PARAMETROS_FORMULARIO = 22;
  public static final int ELIMINAR_COMPONENTE = 19;
  public static final int ELIMINAR_FORMULARIO = 16;
  public static final int AGREGAR_COMPONENTE = 18;
  public static final int CORI = 29;
  public static final int STRING_SPACE = 34;
  public static final int STRING = 25;
  public static final int CORD = 30;
  public static final int CONSULTAS = 26;
  public static final int LOGIN_USUARIO = 14;
  public static final int TEXTO_VISIBLE = 37;
  public static final int OPCIONES = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENQ",
  "ADMIRACION",
  "INI_SOLICITUDES",
  "MAQ",
  "FIN_SOLICITUDES",
  "INI_SOLICITUD",
  "DOS_PUNTOS",
  "CONSULTAR_DATOS",
  "FIN_SOLICITUD",
  "CREAR_USUARIO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "NUEVO_FORMULARIO",
  "ELIMINAR_FORMULARIO",
  "MODIFICAR_FORMULARIO",
  "AGREGAR_COMPONENTE",
  "ELIMINAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "CREDENCIALES_USUARIO",
  "PARAMETROS_FORMULARIO",
  "PARAMETROS_COMPONENTE",
  "COMILLAS",
  "STRING",
  "CONSULTAS",
  "LLAI",
  "LLAD",
  "CORI",
  "CORD",
  "COMA",
  "ID",
  "CONT_ID",
  "STRING_SPACE",
  "TITULO",
  "FORMULARIO",
  "TEXTO_VISIBLE",
  "OPCIONES",
  "CONT_OPCIONES",
  "URL",
  "CONT_URL",
  "CONSULTA_N",
  "CONT_CONSULTA"
  };
}

