
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.reglasGram;

/** CUP generated class containing symbol constants. */
public class symServidor {
  /* terminals */
  public static final int CORI = 19;
  public static final int LLAD = 18;
  public static final int RESPUESTA = 15;
  public static final int CORD = 20;
  public static final int INI_RESPUESTA = 5;
  public static final int FIN_RESPUESTA = 9;
  public static final int BLOQUE = 12;
  public static final int COMILLAS = 13;
  public static final int DOS_PUNTOS = 8;
  public static final int MENQ = 2;
  public static final int COMA = 21;
  public static final int STRING = 16;
  public static final int EOF = 0;
  public static final int FIN_RESPUESTAS = 7;
  public static final int RESPUESTA_SERVIDOR = 11;
  public static final int INI_RESPUESTAS = 4;
  public static final int ADMIRACION = 3;
  public static final int error = 1;
  public static final int USUARIO = 14;
  public static final int LOGIN_USUARIO = 10;
  public static final int LLAI = 17;
  public static final int MAQ = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENQ",
  "ADMIRACION",
  "INI_RESPUESTAS",
  "INI_RESPUESTA",
  "MAQ",
  "FIN_RESPUESTAS",
  "DOS_PUNTOS",
  "FIN_RESPUESTA",
  "LOGIN_USUARIO",
  "RESPUESTA_SERVIDOR",
  "BLOQUE",
  "COMILLAS",
  "USUARIO",
  "RESPUESTA",
  "STRING",
  "LLAI",
  "LLAD",
  "CORI",
  "CORD",
  "COMA"
  };
}

